name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test ./...

      - name: Race detector
        run: go test -race ./...

      - name: Integration tests
        env:
          RTT_USER: ${{ secrets.RTT_USER }}
          RTT_PASSWORD: ${{ secrets.RTT_PASSWORD }}
        run: go test -tags integration ./integration
